#language list:
#vi-VN => Vietnamese
#en-US => English
#hi-IN => Hindi

language: en-US
economy-type:
 provider: economyapi #change it to `bedrockeconomy` if you want use BedrockEconomy!


timezone: "Asia/Ho_Chi_Minh" #See time-zone in website `https://www.php.net/manual/en/timezones.php`
time-to-add-interest: "00:00"
interest: 0.1 #cannot be less than 0, example: `0.1`
